FROM arm32v6/nginx:alpine

COPY configuration/fruitnanny_http /etc/nginx/conf.d/default.conf
COPY configuration/fruitnanny_https /etc/nginx/conf.d/default-ssl.conf
#COPY configuration/.htpasswd /etc/nginx/.htpasswd

